#Sat Jun 07 20:09:58 UTC 2025
curseforge_id=1278719
loader_version_range=[36,)
org.gradle.daemon=false
mapping_channel=parchment
org.gradle.jvmargs=-Xmx3G
minecraft_version_range=[1.16.5,1.17)
mapping_version=2022.03.06-1.16.5
mod_version=2.0.2
mod_name=Mine Mine no Mi\: Player Revive Compatibilty
mod_license=GNU AGPLv3
upload_version_type=release
mod_authors=DerHammerclock
upload_changelog=\# 2.0.2\n\n- Fixed upside down rendering bug\n- Fixed issue that renders pickup progress bar even though the player is not in knockdown mode\n- Fixed issue with player dying the vanilla way instead of bleeding out when "Allow reviving in challenge dimensions" was disabled and player was not in a challenge dimension
mod_group_id=net.hammerclock.mmnm-player-revive-compat
forge_version=36.2.40
mod_id=mmnmrevive
forge_version_range=[36,)
mod_description=This introduces a compatibility layer with Mine Mine no Mi
minecraft_version=1.16.5
