#Wed Jun 04 01:39:45 UTC 2025
curseforge_id=1278719
loader_version_range=[36,)
org.gradle.daemon=false
mapping_channel=parchment
org.gradle.jvmargs=-Xmx3G
minecraft_version_range=[1.16.5,1.17)
mapping_version=2022.03.06-1.16.5
mod_version=2.0.0
mod_name=Mine Mine no Mi\: Player Revive Compatibilty
mod_license=GNU AGPLv3
upload_version_type=release
mod_authors=DerHammerclock
upload_changelog=\# 2.0.0\n\n\#\# \!\!\! BREAKING CHANGES\!\!\!\n\n<strong>Now required on the client as well for any further 2.x.x version</strong>\n\n- Updated to Mine Mine no Mi 0.10.6\n- Added new config option to give knockdown to players that are bleeding out\n- Added new functionality to carry players that are bleeding out and are knocked out on long press\n- Fixed challenge fix not working properly\n- Giant code refactor and easier publishing via gradle\n- Now also on CurseForge\!\n
mod_group_id=net.hammerclock.mmnm-player-revive-compat
forge_version=36.2.40
mod_id=mmnmrevive
forge_version_range=[36,)
mod_description=This introduces a compatibility layer with Mine Mine no Mi
minecraft_version=1.16.5
