#Mon May 12 20:33:35 CEST 2025
loader_version_range=[36,)
org.gradle.daemon=false
modrinth_changelog=\# 1.3.0\n\n- Fixed dying in a challenge dimension will actually kill you\n- Changed immediate death config option to an option that allows other players to revive you in challenge dimensions\n- Updated to Mine Mine no Mi 0.10.5\n
mapping_channel=parchment
org.gradle.jvmargs=-Xmx3G
minecraft_version_range=[1.16.5,1.17)
mapping_version=2022.03.06-1.16.5
mod_version=1.4.0
mod_name=Mine Mine no Mi\: Player Revive Compatibilty
modrinth_version_type=release
mod_license=GNU AGPLv3
mod_authors=DerHammerclock
mod_group_id=net.hammerclock.mmnm-player-revive-compat
forge_version=36.2.40
mod_id=mmnmrevive
forge_version_range=[36,)
mod_description=This introduces a compatibility layer with Mine Mine no Mi
minecraft_version=1.16.5
