modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/rathmerdominik/player-revive-compat/issues/"

[[mods]]
	modId="${mod_id}"
	version="${mod_version}"
	displayName="${mod_name}"
	updateJSONURL="https://raw.githubusercontent.com/rathmerdominik/player-revive-compat/main/updates.json"
	displayURL="https://github.com/rathmerdominik/player-revive-compat/"
	logoFile="mmnmrevive.png"
	credits="DerHammerclock"
	authors="${mod_authors}"
	description='''${mod_description}'''

[[dependencies.mineminenomi]] 
	modId = "mineminenomi"
	mandatory = true
	versionRange = "[0.10.1,)"
	ordering = "AFTER"
	side = "SERVER"

[[dependencies.playerrevive]]
	modId="playerrevive"
	mandatory=true
	versionRange="[2.0.0,)"
	ordering="AFTER"
	side="SERVER"
